### ISSUE TITLE
Hypnos Lullaby V2 Mechanics Crashing

### ISSUE THREAD

**Issue by riversedgeranch** [BeastlyGabi/Forever-Engine-Archive#6]
### Describe the bug

When I try to load week 1 of the Hypnos Lullaby V2 mod, if mechanics are set to pussy(off), trying to load the first week crashes the game.

### Have you modified the engine in any way prior to reporting this bug?

No

### Provide the log that the terminal outputs

meta/state/PlayState.hx (line 2313)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/Yoshubs/Forever-Engine

**Comment by Ploxycamente2** [comment]
fuck you, if you have an error in hypno's lullaby make an issue in hypno's lullaby source code

**Comment by BeastlyGabi** [comment]
hypno as a mod is _cancelled_ and _finished_, bugs won't be fixed, nor will I accept bugs from it here.
